#!/bin/bash

source "$HOME/okaeri/config/boot"
source "$OKAERI_PATHS_SCRIPT"

# Exports

export OKAERI_PATH
export OKAERI_VERSION

export OKAERI_HOSTNAME

export OKAERI_INITIALIZE_SCRIPT
export OKAERI_PATHS_SCRIPT

export OKAERI_DOCKER_VOLUMES_PATH
export OKAERI_BUILD_PATH
export OKAERI_DUMP_PATH
export OKAERI_TMP_PATH
export OKAERI_TOOLS_PATH
export OKAERI_WORK_PATH

echo "Okaeri $OKAERI_VERSION"

# VS Code

alias code="flatpak run com.visualstudio.code &>/dev/null"
alias bake="rake --rakefile $OKAERI_PATH/usr/lib/projects/setup/Rakefile"

## Working Directories

if [ ! -d $OKAERI_DOCKER_VOLUMES_PATH ]; then
  mkdir $OKAERI_DOCKER_VOLUMES_PATH
  touch "$OKAERI_DOCKER_VOLUMES_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_BUILD_PATH ]; then
  mkdir $OKAERI_BUILD_PATH
  touch "$OKAERI_BUILD_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_DUMP_PATH ]; then
  mkdir $OKAERI_DUMP_PATH
  touch "$OKAERI_DUMP_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_LOG_PATH ]; then
  mkdir $OKAERI_LOG_PATH
  touch "$OKAERI_LOG_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_TMP_PATH ]; then
  mkdir $OKAERI_TMP_PATH
  touch "$OKAERI_TMP_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_TOOLS_PATH ]; then
  mkdir $OKAERI_TOOLS_PATH
  touch "$OKAERI_TOOLS_PATH/.ignore-sync"
fi

if [ ! -d $OKAERI_WORK_PATH ]; then
  mkdir $OKAERI_WORK_PATH
fi

## Prompt

function parse_git_branch () {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
NO_COLOUR="\[\033[0m\]"

PS1="$YELLOW\h$NO_COLOUR \W$GREEN\$(parse_git_branch)$NO_COLOUR \$ "