#!/bin/bash

source "$HOME/okaeri/config/boot"

# Exports

export OKAERI_PATH
export OKAERI_VERSION

export OKAERI_DOCKER_VOLUMES_PATH
export OKAERI_TMP_PATH
export OKAERI_WORK_PATH

export PATH="$OKAERI_PATH/usr/bin:$PATH"

# VS Code

alias code="flatpak run com.visualstudio.code &>/dev/null"
alias bake="rake --rakefile $OKAERI_PATH/lib/projects/setup/Rakefile"

# RB Env

if [ -d "$HOME/.rbenv" ]; then
	export PATH="$HOME/.rbenv/bin:$PATH"
fi

echo "Okaeri $OKAERI_VERSION"