#!/bin/bash

# eb - AWS Elastic Beanstalk command line tool

if [ -d "$HOME/.ebcli-virtual-env/executables" ]; then
  export PATH="$HOME/.ebcli-virtual-env/executables:$PATH"
fi

## SQLPackage

if [ -d "$OKAERI_TOOLS_PATH/sqlpackage" ]; then
  export PATH="$OKAERI_TOOLS_PATH/sqlpackage:$PATH"
fi

export PATH="$OKAERI_PATH/usr/bin:./bin:$PATH"