#!/bin/bash

set -e

source "$HOME/okaeri/config/boot"

echo
echo
echo "Oakeri - Setup"
echo "=============="
echo
echo "You are about to setup okaeri core tools on your system. You will be asked for your sudo password."
echo
echo
echo "If setup aborts or fails, call the following script to re-enable packagekit."
echo
echo "$OKAERI_PATH/core/scripts/packagekit-start"
echo
echo
echo "Your current machine name is: $OKAERI_HOSTNAME"
echo
echo

read -p "Do you want to continue? (y/n) " answer

case "$answer" in
	[Yy]* )
		echo
		echo "Continuing..."
		echo
		;;
	[Nn]* )
		echo
		echo "Exiting..."
		echo
		exit 1
		;;
	* )
		echo
		echo "Invalid input. Please enter y or n."
		echo
		exit 1
		;;
esac

. $OKAERI_INITIALIZE_SCRIPT

source "$OKAERI_PATH/core/scripts/packagekit-stop"

sudo apt --yes update

sudo apt --yes upgrade

source "$OKAERI_PATH/core/config/desktop"
source "$OKAERI_PATH/core/config/git"

source "$OKAERI_PATH/core/tools/developer-essentials"
source "$OKAERI_PATH/core/tools/flatpak-desktop-tools"
source "$OKAERI_PATH/core/tools/docker"
source "$OKAERI_PATH/core/tools/rbenv"
source "$OKAERI_PATH/core/tools/rclone"
source "$OKAERI_PATH/core/tools/sqlpackage"

. $OKAERI_INITIALIZE_SCRIPT

source "$OKAERI_PATH/core/languages/php"

source "$OKAERI_PATH/usr/bin/rbenv-update"
source "$OKAERI_PATH/core/languages/ruby"

. $OKAERI_INITIALIZE_SCRIPT

sudo apt --yes autoremove

source "$OKAERI_PATH/core/scripts/packagekit-start"

echo
echo
echo "Oakeri - Setup complete"
echo "======================="
echo
echo "Restart your machine to complete the setup."
echo
echo