#!/bin/bash

set -e

source "$HOME/okaeri/config/boot"

sudo apt update

sudo apt upgrade --yes

source "$OKAERI_PATH/core/config/desktop"
source "$OKAERI_PATH/core/config/git"

source "$OKAERI_PATH/core/tools/developer-essentials"
source "$OKAERI_PATH/core/tools/docker"
source "$OKAERI_PATH/core/tools/rbenv"
source "$OKAERI_PATH/core/tools/rclone"
source "$OKAERI_PATH/core/tools/sqlpackage"

. $OKAERI_INITIALIZE_SCRIPT

source "$OKAERI_PATH/usr/bin/rbenv-update"
source "$OKAERI_PATH/core/languages/ruby"

. $OKAERI_INITIALIZE_SCRIPT

sudo apt autoremove --yes

echo
echo
echo "Oakeri - Setup complete"
echo "======================="
echo
echo "Restart your machine to complete setup (reboot necessary for docker)"
echo
echo