#!/bin/bash

echo
echo
echo "Oakeri - Tools - developer essentials"
echo "====================================="
echo

sudo apt --yes update

sudo apt --yes install software-properties-common

sudo add-apt-repository --yes ppa:git-core/ppa

sudo apt --yes install \
	autoconf \
	awscli \
	bison \
	build-essential \
	ca-certificates \
	curl \
	gnupg \
	default-jre \
	git \
	imagemagick \
	libmagickcore-dev \
	libmagickwand-dev \
	jq \
	libffi-dev \
	libgdbm-dev \
	libmysqlclient-dev \
	libncurses5-dev \
	libpq-dev \
	libreadline-dev \
	libssl-dev \
	libyaml-dev \
	lsb-release \
	openssh-server \
	pkg-config \
	pv \
	tree \
	zlib1g-dev

sudo apt --yes autoremove