#!/bin/bash

echo
echo
echo "Oakeri - Tools - rbenv"
echo "======================"
echo

sudo apt --yes update

sudo apt --yes remove \
	rbenv \
	ruby-build \
	|| true

rbenv="$(command -v rbenv | head -1)"

if [[ ! -n "$rbenv" ]]; then
	curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
else
	echo
	echo
	echo "rbenv already installed"
	echo
	echo
fi

sudo apt --yes autoremove