#!/bin/bash

echo
echo
echo "Oakeri - Tools - rclone"
echo "======================="
echo

sudo apt -o DPkg::Lock::Timeout=30 update

sudo apt remove --yes \
	rclone \
	|| true

rclone="$(command -v rclone | head -1)"

if [ ! -n "$rclone" ]; then
	sudo -v ; curl https://rclone.org/install.sh | sudo bash
else
	echo
	echo
	echo "rclone already installed, running \`rclone selfupdate\` instead"
	echo
	echo
	rclone selfupdate
fi



sudo apt autoremove --yes