#!/bin/bash

echo
echo
echo "Oakeri - Tools - rclone"
echo "======================="
echo

sudo apt --yes update

sudo apt --yes remove \
	rclone \
	|| true

rclone="$(command -v rclone | head -1)"

if [ ! -n "$rclone" ]; then
	sudo -v ; curl https://rclone.org/install.sh | sudo bash
else
	echo
	echo
	echo "rclone already installed, running \`rclone selfupdate\` instead"
	echo
	echo
	rclone selfupdate
fi



sudo apt --yes autoremove