#!/bin/bash

echo
echo
echo "Oakeri - Tools - Virtual Machines"
echo "================================="
echo

sudo apt --yes update

sudo apt --yes install \
	qemu-kvm \
	libvirt-daemon-system \
	libvirt-clients \
	bridge-utils \
	virt-manager

sudo apt --yes autoremove