#!/bin/bash

sudo apt --yes update

sudo apt --yes  remove nodejs \
    npm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

echo ""
echo "nvm ready for usage"
echo "==================="
echo ""
echo "Open a new terminal and install the latest long term support version."
echo ""
echo "nvm install --lts"
echo ""

sudo apt --yes  autoremove