#!/bin/bash

sudo apt -o DPkg::Lock::Timeout=60 --yes update

sudo add-apt-repository --yes ppa:ondrej/php

sudo apt -o DPkg::Lock::Timeout=60 --yes install  \
    php-cli

sudo apt -o DPkg::Lock::Timeout=60 --yes autoremove