#!/bin/bash

if [ ! -d "$HOME/.rbenv" ]; then
    echo "You need to run \`core/setup\` first to install rbenv"
    exit 1
fi

RUBY_VERSION=3.4.6

rbenv install $RUBY_VERSION --skip-existing
rbenv global $RUBY_VERSION
