#!/bin/bash

source "$HOME/okaeri/config/boot"

# Desktop layout - remove background image

gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background picture-uri ""

# Desktop layout - set background color

gsettings set org.gnome.desktop.background primary-color "#304656"
gsettings set org.gnome.desktop.background secondary-color "#304656"
gsettings set org.gnome.desktop.background color-shading-type "solid"

# Setup APT PPA maintained repositories

sudo apt update
sudo apt install software-properties-common

sudo add-apt-repository ppa:git-core/ppa

## APT Packages

sudo apt update

sudo apt -y install \
	git \
	jq \
	awscli \
	ruby-build \
	libmysqlclient-dev \
	libpq-dev \
	openssh-server \
	nodejs \
	npm \
	php-cli \
	default-jre \
	pv



sudo apt autoremove
