#!/bin/bash

source "$HOME/okaeri/config/boot"

# Desktop layout - remove background image

gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background picture-uri ""

# Desktop layout - set background color

gsettings set org.gnome.desktop.background primary-color "#304656"
gsettings set org.gnome.desktop.background secondary-color "#304656"
gsettings set org.gnome.desktop.background color-shading-type "solid"

# Setup APT PPA maintained repositories

sudo apt update
sudo apt install software-properties-common

sudo add-apt-repository ppa:git-core/ppa

## APT Packages

sudo apt update

sudo apt -y install \
	awscli \
	ca-certificates \
	curl \
	gnupg \
	default-jre \
	git \
	jq \
	libmysqlclient-dev \
	libpq-dev \
	lsb-release \
	nodejs \
	npm \
	openssh-server \
	php-cli \
	pv \
	ruby-build

## Docker

sudo apt remove docker docker-engine docker.io containerd runc

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update

sudo apt install \
	containerd.io \
	docker-buildx-plugin \
	docker-ce \
	docker-ce-cli \
	docker-compose-plugin

sudo chmod 666 /var/run/docker.sock

sudo service docker status

## APT cleanup

sudo apt autoremove
